{{- if .Values.nomad.enabled -}}
{{- $config := .Values.nomad.config -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nomad.fullname" . }}-gpuworker
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
    app.kubernetes.io/component: gpuworker
spec:
  replicas: {{ .Values.nomad.gpuworker.replicaCount }}
  selector:
    matchLabels:
      {{- include "nomad.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gpuworker
  template:
    metadata:
      {{- with .Values.nomad.gpuworker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- if $.Values.roll }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
      {{- else }}
      {{- if .Values.roll }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "nomad.labels" . | nindent 8 }}
        {{- with .Values.nomad.gpuworker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: gpuworker
    spec:
      {{- with .Values.nomad.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nomad.serviceAccountName" . }}
      {{- with .Values.nomad.gpuworker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-gpuworker
          {{- with .Values.nomad.gpuworker.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.nomad.gpuworker.image.repository }}
          image: "{{ .Values.nomad.gpuworker.image.repository }}:{{ .Values.nomad.gpuworker.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.nomad.image.repository }}:{{ .Values.nomad.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.nomad.image.pullPolicy }}
          {{- with .Values.nomad.gpuworker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /app/nomad.yaml
              name: nomad-conf
              subPath: nomad.yaml
            - mountPath: /app/.volumes/fs/public
              name: public-volume
            - mountPath: /app/.volumes/fs/staging
              name: staging-volume
            - mountPath: /nomad
              name: nomad-volume
            {{- with .Values.nomad.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.nomad.gpuworker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: MPLCONFIGDIR
              value: /tmp/matplotlib
            - name: CELERY_ACKS_LATE
              value: "True"
            - name: NOMAD_META_SERVICE
              value: "worker"
            - name: NOMAD_CONSOLE_LOG_LEVEL
              value: "{{ $config.logging.worker.console_loglevel }}"
            - name: NOMAD_LOGSTASH_LEVEL
              value: "{{ $config.logging.worker.logstash_loglevel }}"
            - name: NOMAD_CELERY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- if .Values.nomad.secrets.api.secretName }}
            - name: NOMAD_SERVICES_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nomad.secrets.api.secretName }}
                  key: password
            {{- end }}
            {{- if .Values.nomad.secrets.keycloak.clientSecretName }}
            - name: NOMAD_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nomad.secrets.keycloak.clientSecretName }}
                  key: password
            {{- end }}
            {{- if .Values.nomad.secrets.keycloak.passwordSecretName }}
            - name: NOMAD_KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nomad.secrets.keycloak.passwordSecretName }}
                  key: password
            {{- end }}
          # See https://keithtenzer.com/temporal/Deploying_Temporal_Worker_on_Kubernetes/#liveliness-and-readiness-probes
          # for rationale on using 'ls /' as a liveness/readiness probe for Temporal workers.
          command: ["python", "-m", "nomad.cli", "admin", "run", "action-gpu-worker"]
          readinessProbe:
            exec:
              command:
              - ls
              - /
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
              - ls
              - /
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
      {{- with .Values.nomad.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.gpuworker.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: nomad-conf
          configMap:
            name: {{ include "nomad.fullname" . }}-configmap
        - name: public-volume
          hostPath:
            path: {{ $config.fs.public_external }}
            # type: Directory
        - name: staging-volume
          {{ if (eq .Values.nomad.worker.storage "memory") }}
          emptyDir:
            medium: 'Memory'
          {{ else }}
          hostPath:
            path: {{ $config.fs.staging_external }}
            # type: Directory
          {{ end }}
        - name: nomad-volume
          hostPath:
            path: {{ $config.fs.nomad }}
            # type: Directory

      {{- with .Values.nomad.gpuworker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.gpuworker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.gpuworker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
