services:
  api_host: 'localhost'
  api_base_path: '/nomad-oasis'

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: '978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d'

meta:
  deployment: 'oasis'
  deployment_url: 'https://my-oasis.org/api'
  maintainer_email: 'me@my-oasis.org'

logstash:
  enable: false

mongo:
    db_name: nomad_oasis_v1

elastic:
    entries_index: nomad_oasis_entries_v1
    materials_index: nomad_oasis_materials_v1

plugins:
  include:
    - 'schemas/ikz_pld'
    - 'parsers/nomad_measurements/xrd'
  options:
    parsers/nomad_measurements/xrd:
      python_package: nomad_measurements.xrd
    schemas/nomad_measurements:
      python_package: nomad_measurements
    schemas/ikz_pld:
      python_package: ikz_pld